* SMS Simulation

** Installing dependencies
Need to make sure that poetry is installed on your system. This link should
provide instructions on how to install poetry:
https://python-poetry.org/docs/#installation

Once poetry is installed the following command can be used to install all
dependencies: ~poetry install~

** Configuring parameters
The ~simulation_config.toml~ file will be used to control different parameters
used by the different portions of the simulation. The different sections and
their parameters are outlined below.
*** msg_producer
**** num_msgs_to_send
Default: 1000 messages

The number of messages that are contained in the message pool.
*** msg_sender
**** average_send_time
Defalut: 5 seconds
The number of seconds that it takes to send a message.
**** average_send_time_factor
Default: 3 seconds

The number of seconds plus or minus from the ~average_send_time~ that it can
take to send a message. For example if ~average_send_time = 5~ and
~average_send_time_factor = 2~ messages could be sent anywhere in the range of
3 - 7 seconds.
**** failure_rate
Defalut: 25%

The approximate rate of failure as a percentage for each sender.
**** num_senders
Default: 50 senders

The number of senders that will be used to send messages.
*** progress_monitor
**** refresh_rate
Default: 5 seconds

The number of seconds to wait before refreshing the progress monitor.

** Running the simulation
After installing the required dependencies the simulation can be run using the
following command: ~poetry run python main.py~

** Checking logs
The overall log of all message transactions can be found at ~sms_msgs.log~

** Running tests
To run all test cases for the project simply run the following command: ~poetry
run pytest~
